#Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/Abunuo"
  zhihu: "https://www.zhihu.com/people/abunuo/activities"
  # mail: "http://liangmingqing315@163.com"
  # qq: "#"
  weibo: "http://weibo.com/u/3908506607/home?topnav=1&wvr=6"
  # rss: "#"
  #douban: "#"
  facebook: "https://www.facebook.com/profile.php?id=100014780655438"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: 阅读全文
# excerpt_link: more
fancybox: true
mathjax: true

#widgets: #配置页脚显示哪些小挂件
#  - category
#  - tags
#  - tagcloud
#  - recent_posts
#  - blogroll

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# 百度统计、谷歌统计
# baidu_tongji: true
# google_analytics: true

favicon: /img/1030.gif

#你的头像url
avatar: /img/head.jpg

#是否开启分享
share: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
# duoshuo: your duoshuo id

#是否开启云标签
tagcloud: true

#是否开启文章阅读量
leancloud_visitors:
  enable: false
  app_id: your_app_id
  app_key: your_app_key


#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  smackdown: https://github.com/winnerweb/hexo-theme-smackdown
#是否开启“关于我”。
# 不开启——
#aboutme: true
#开启——
aboutme: "Line code fun: people did not, the code is still.."

swift_search:
  enable: true
